'use client';

export const metadata = {
    title: 'Contacts',
    description: 'Generated by create next app',
}


//-- Contacts 
const Contacts = () => {
    return(
        <h1>contacts page</h1>
    )
}

export default Contacts;