import '../styles/style.scss';
import { Inter } from 'next/font/google'
import Header from '../components/header/Header';
import Footer from '../components/footer/Footer';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}


const RootLayout = ({ children }) => {
    return (
        <html lang="en">
            <body>
                <div className="wrapper">
                    <Header/>
                        <main className="main">
                            {children}
                        </main>
                    <Footer/>
                </div>
            </body>
        </html>
    )
}

export default RootLayout;